Slug updated twice
apostrophecms/apostrophe-workflow pull request #333
Opened 2021-03-01 18:05 UTC by ValJed

With workflow, when we commit a page move, the slug is updated using the draft one in workflow. Then it calls the `self.move` method of `apostrophe-pages`, inside the slug is re updated.
This behavior produces bad slugs by duplicating it, example **/block-page/sub-page** becomes **/block-page/block-page/sub-page**.

2021-03-01 19:57 UTC, abea reviewed
Maybe the Apostrophe core `peerDependencies` version should be updated to the version where you fixed it in core.

2021-03-01 21:14 UTC, boutell requested changes
peerDependencies could be left alone because it works as well as before if apostrophe is not updated, but I think it is worth updating it.

Otherwise great.

2021-03-02 14:04 UTC, boutell approved these changes

2021-03-02 17:31 UTC, ValJed commented
PeerDependencies for apostrophe has been upgraded.

2021-03-02 17:41 UTC, boutell approved these changes

2021-03-04 13:30 UTC, boutell approved these changes

2021-03-08 13:43 UTC, merged