Fix assembly bug when creating site
apostrophecms/apostrophe-workflow pull request #341
Opened 2021-06-24 17:53 UTC by ValJed

## Purpose
Issue when creating a website on an Assembly project using the `apostrophe-headless` module. 
The `modulesReady` callback was missing so the website creation was loading infinitely

2021-06-24 18:13 UTC, abea requested changes

2021-06-24 18:13 UTC, abea commented on lib/modules/apostrophe-workflow-pages/index.js
> +          callback(err);
We should return this callback.

2021-06-24 18:13 UTC, abea commented on CHANGELOG.md
> +## 2.39.3 (2021-06-24)
Don't date it quite yet.

2021-06-28 13:38 UTC, boutell requested changes
This fix is urgent at this point, yes? Right now workflow and headless are incompatible.

You have run into one of the reasons we deprecated callAll methods like modulesReady: it's very hard to know if the other modules in your inheritance chain are using async versions or not.

So please switch this to a promise event handler for maximum compatibility:

`self.on('apostrophe:modulesReady', 'setAutoCommitPageMoves', function() { ... })`

I know there are other instances of modulesReady as a callAll method and we need to leave those alone for bc reasons at this late date, but we can at least fix this newly introduced one because it constitutes a bug anyway in its current form.

2021-06-28 14:55 UTC, abea approved these changes

2021-06-28 16:04 UTC, boutell approved these changes

2021-06-28 16:04 UTC, merged